# -*- coding: utf-8 -*-
"""Food_production_data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMkojs7x1qfG9Vp894h6W85VqlJw5-k2
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

# Load the dataset
file_path = "/content/drive/MyDrive/Food_Production2.csv"
df = pd.read_csv(file_path)

# Basic checks
print("Shape of dataset:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

# Preview first 5 rows
df.head()

"""Data Cleaning"""

# Check dataset info
df.info()

# Count missing values per column
missing = df.isnull().sum().sort_values(ascending=False)
print(missing)

# Check total number of duplicate rows
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

print(df["Food product"].values)

# Show rows with missing values
rows_with_missing = df[df.isnull().any(axis=1)]
print(rows_with_missing.shape)  # number of rows with missing values
rows_with_missing.head(19)

# Find missing values by row and column
missing_map = {}

for idx, row in df[df.isnull().any(axis=1)].iterrows():
    missing_cols = row[row.isnull()].index.tolist()
    missing_map[row['Food product']] = missing_cols

# Display neatly
for food, cols in missing_map.items():
    print(f"{food}: {cols}")

from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

# Make a copy BEFORE imputation
df_before = df.copy()

# Select numeric columns only (exclude Food product)
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
numeric_df = df[numeric_cols]

#  Scale the data (important for KNN distance calculation)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

#  Apply KNN Imputer
imputer = KNNImputer(n_neighbors=5)
imputed_scaled = imputer.fit_transform(scaled_data)

#  Inverse scale back to original values
imputed_data = scaler.inverse_transform(imputed_scaled)

#  Put back into DataFrame
imputed_df = pd.DataFrame(imputed_data, columns=numeric_cols)

#  Replace numeric columns in original dataframe
df[numeric_cols] = imputed_df


# Check if any missing values remain
print("✅ Missing values after imputation:")
print(df.isnull().sum())

print(df.head(10))

# Save the cleaned dataset
df.to_csv("food_emissions_imputed.csv", index=False)

print("💾 Cleaned dataset saved as 'food_emissions_imputed.csv'")

from google.colab import files

# Download CSV
files.download("food_emissions_imputed.csv")